version: '3.6'

services:
  db:
    build: ./dockpgsql
    ports:
      - "5432:5432"
  mem:
    image: memcached:1.5.7
    ports:
      - "11211:11211"
  web:
    build: ./dock1
    volumes:
      - ./dock1/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mem